import { MigrationInterface, QueryRunner } from "typeorm";

export class undefinedigration1686687521714 implements MigrationInterface {
    name = 'undefinedigration1686687521714'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_payment_methods" DROP CONSTRAINT "FK_de52ee40aabfbe3eef30992bf65"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_37c274a69a761e87c799fe4e7e1"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_1e141aeaf8d6fabca9c1c823936"`);
        await queryRunner.query(`CREATE TABLE "login_tracker" ("id" SERIAL NOT NULL, "lastLogin" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" integer, CONSTRAINT "REL_9a96c66dd49d52bfdca62e7dc2" UNIQUE ("userId"), CONSTRAINT "PK_ae01735fd8d07012f00a8c0c0ff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tickets_tickettype_enum" AS ENUM('FSE', 'FTE', 'PTE')`);
        await queryRunner.query(`CREATE TABLE "tickets" ("id" SERIAL NOT NULL, "cogentCaseNumber" character varying NOT NULL, "cogentWorkOrderNumber" text array, "ticketType" "public"."tickets_tickettype_enum" NOT NULL, "isExternal" boolean NOT NULL DEFAULT false, "numberOfHoursReq" character varying NOT NULL, "numberOfResource" character varying NOT NULL, "ticketDetailId" character varying NOT NULL, "ticketReceivedTime" TIMESTAMP WITH TIME ZONE NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_343bc942ae261cf7a1377f48fd0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "vendorName"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "engagementType"`);
        await queryRunner.query(`DROP TYPE "public"."users_engagementtype_enum"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "rpocName"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "rpocEmail"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "rpocContactNumber"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "idCardNumber"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "taxNumber"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "languages"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "skillSet"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "availableTools"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "nationality"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "region"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "country"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "state"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "city"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "postalCode"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "whatsappNumber"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "cogentEmail"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "descriptionColor"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "hourlyRate"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "halfDayRate"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "fullDayRate"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "monthlyRate"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "anyExtraRate"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "transport"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "mobility"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "isOnboarded"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "isARequest"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "onboardedAt"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "idCardType"`);
        await queryRunner.query(`DROP TYPE "public"."users_idcardtype_enum"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "whatsappGroup"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "whatsappGroupLink"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "workPermitStatus"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "availability"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "resumeDocUrl"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "identityDocUrl"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "mobileNumber"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "contactNumber"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "contractDocuments"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "addressLine1"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "addressLine2"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "interviewStatus"`);
        await queryRunner.query(`DROP TYPE "public"."users_interviewstatus_enum"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "requestApproved"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "onboardedBy"`);
        await queryRunner.query(`ALTER TYPE "public"."roles_role_enum" RENAME TO "roles_role_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."roles_role_enum" AS ENUM('rms', 'sd', 'resource', 'feops', 'admin', 'customer')`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "role" TYPE "public"."roles_role_enum" USING "role"::"text"::"public"."roles_role_enum"`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "role" SET DEFAULT 'resource'`);
        await queryRunner.query(`DROP TYPE "public"."roles_role_enum_old"`);
        await queryRunner.query(`ALTER TABLE "user_payment_methods" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "user_payment_methods" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_37c274a69a761e87c799fe4e7e1" FOREIGN KEY ("loginTrackerId") REFERENCES "login_tracker"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "login_tracker" ADD CONSTRAINT "FK_9a96c66dd49d52bfdca62e7dc28" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "login_tracker" DROP CONSTRAINT "FK_9a96c66dd49d52bfdca62e7dc28"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_37c274a69a761e87c799fe4e7e1"`);
        await queryRunner.query(`ALTER TABLE "user_payment_methods" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "user_payment_methods" ADD "userId" integer`);
        await queryRunner.query(`CREATE TYPE "public"."roles_role_enum_old" AS ENUM('rms', 'sd', 'resource', 'feops', 'admin')`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "role" TYPE "public"."roles_role_enum_old" USING "role"::"text"::"public"."roles_role_enum_old"`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "role" SET DEFAULT 'resource'`);
        await queryRunner.query(`DROP TYPE "public"."roles_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."roles_role_enum_old" RENAME TO "roles_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "onboardedBy" integer`);
        await queryRunner.query(`ALTER TABLE "users" ADD "requestApproved" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`CREATE TYPE "public"."users_interviewstatus_enum" AS ENUM('Complete', 'Scheduled', 'NotScheduled')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "interviewStatus" "public"."users_interviewstatus_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "addressLine2" text`);
        await queryRunner.query(`ALTER TABLE "users" ADD "addressLine1" text`);
        await queryRunner.query(`ALTER TABLE "users" ADD "contractDocuments" boolean`);
        await queryRunner.query(`ALTER TABLE "users" ADD "contactNumber" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "mobileNumber" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "identityDocUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "resumeDocUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "availability" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "workPermitStatus" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "whatsappGroupLink" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "whatsappGroup" character varying`);
        await queryRunner.query(`CREATE TYPE "public"."users_idcardtype_enum" AS ENUM('DriverLicense', 'Passport', 'IdCard', 'ResidencePermit')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "idCardType" "public"."users_idcardtype_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "onboardedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "users" ADD "isARequest" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "isOnboarded" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "mobility" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "transport" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "anyExtraRate" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "monthlyRate" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "fullDayRate" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "halfDayRate" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "hourlyRate" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "descriptionColor" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "cogentEmail" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "whatsappNumber" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "postalCode" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "city" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "state" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "country" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "region" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "nationality" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "availableTools" text array`);
        await queryRunner.query(`ALTER TABLE "users" ADD "skillSet" text array`);
        await queryRunner.query(`ALTER TABLE "users" ADD "languages" text array`);
        await queryRunner.query(`ALTER TABLE "users" ADD "taxNumber" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "idCardNumber" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "rpocContactNumber" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "rpocEmail" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "rpocName" character varying`);
        await queryRunner.query(`CREATE TYPE "public"."users_engagementtype_enum" AS ENUM('Fse', 'Fte', 'Pte', 'Remote')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "engagementType" "public"."users_engagementtype_enum" DEFAULT 'Fse'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "vendorName" character varying`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('Direct', 'Indirect')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "status" "public"."users_status_enum" DEFAULT 'Direct'`);
        await queryRunner.query(`DROP TABLE "tickets"`);
        await queryRunner.query(`DROP TYPE "public"."tickets_tickettype_enum"`);
        await queryRunner.query(`DROP TABLE "login_tracker"`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_1e141aeaf8d6fabca9c1c823936" FOREIGN KEY ("onboardedBy") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_37c274a69a761e87c799fe4e7e1" FOREIGN KEY ("loginTrackerId") REFERENCES "loginTracker"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_payment_methods" ADD CONSTRAINT "FK_de52ee40aabfbe3eef30992bf65" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
