apiVersion: v1
kind: Service
metadata:
  name: {{ template "relname" . }}-client
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "relname" . }}
    component: client
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http-web
  selector:
    app: {{ template "relname" . }}
    component: client
