apiVersion: v1
kind: Service
metadata:
  name: {{ template "relname" . }}-erp
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "relname" . }}
    component: erp
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP
    name: http-erp
  selector:
    app: {{ template "relname" . }}
    component: erp
